#! /usr/bin/env bash

#=========================================================================#
#                                   phd                                   #
#                                                                         #
# Author: nic                                                             #
# Date: 2017-Aug-08                                                       #
#                                                                         #
# Options:                                                                #
#   -h           Display this help message                                #
#=========================================================================#

set -e # error on non-zero exit
set -u # undefined variables are an error

WC_F="/tmp/PHD_WC"
CG_F="/tmp/PHD_CONGRATS"

function usage(){
    grep "^#.*#$" $0
}

function errxit(){
    [ $# -gt 0 ] && echo "Error: $@" >&2
    echo "Re-run with -h for help" >&2
    exit 1
}

function get(){
    wc -w ~/uni/tex/phd/*.tex | tail -n 1 | sed -e 's/^ *//' -e 's/ .*$//'
}

while getopts "h" opt; do
    case $opt in
        h)
            usage
            exit 0
            ;;
        \?)
            errxit Unrecognised command
            ;;
    esac
done
shift $(($OPTIND -1))

if [ -f "$WC_F" ] && [ $(date -r "$WC_F" +%d) != $(date +%d) ]; then
    rm -f "$WC_F" "$CG_F"
fi

if [ ! -f "$WC_F" ]; then
    get > "$WC_F"
fi

AMT=$(cat "$WC_F")
CUR=$(get)
DIF=$(( $CUR - $AMT ))
echo $AMT +$DIF

if [ $DIF -gt 1000 ] && [ ! -f "$CG_F" ]; then
    echo "you have been congratulated" > "$CG_F"
    notify-send "Congrats" "You just passed 1000 words"
fi
