# Music
music_directory    "/home/nic/Music"

# Put local state in $XDG_DATA
db_file            "/home/nic/.local/share/mpd/database"
playlist_directory "/home/nic/.local/share/mpd/playlists"
#pid_file          "/home/nic/.local/share/mpd/pid"
#state_file        "/home/nic/.local/share/mpd/state"
#sticker_file      "/home/nic/.local/share/mpd/sticker.sql"

# Logs to systemd journal
log_file           "syslog"

# Keep db up-to-date
auto_update "yes"

# Configs for pulse audio.
audio_output {
    type           "pulse"
    name           "pulse audio"
}

# Additional output for ncmpcpp visualizer
# c.o. arch wiki
audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}
